# Generated by Django 5.2.7 on 2025-10-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
    ]
