# Generated by Django 5.2.7 on 2025-10-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_position_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
