# Generated by Django 5.2.1 on 2025-11-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='section',
            field=models.CharField(choices=[('todo', 'To-Do'), ('immediate', 'Immediate'), ('later', 'Later'), ('finished', 'Finished')], default='todo', max_length=20),
        ),
    ]
